#ifndef __TRAFFIC_LIGHTS__
#define __TRAFFIC_LIGHTS__

#define TL_RED_PORT    HAL_GPIO_PORTB
#define TL_YELLOW_PORT HAL_GPIO_PORTB
#define TL_GREEN_PORT  HAL_GPIO_PORTB

#define TL_RED_PIN     HAL_GPIO_PIN4
#define TL_YELLOW_PIN  HAL_GPIO_PIN5
#define TL_GREEN_PIN   HAL_GPIO_PIN6

#endif