if(STM32_CPU STREQUAL "STM32F103C8T6")
   set(STM32_C_FLAGS ${STM32_C_FLAGS} -DSTM32F1 -DSTM32F103C8T6 -D_ROM=64K -D_RAM=20K -D_ROM_OFF=0x08000000 -D_RAM_OFF=0x20000000)
   set(OPENCM3HAL_PATH ${CMAKE_CURRENT_LIST_DIR}/opencm3hal/stm32f1)
   set(LINKER_FILE ${OPENCM3HAL_PATH}/stm32f103x8.ld)
   target_link_libraries(${EXECUTABLE} opencm3_stm32f1)
elseif(STM32_CPU STREQUAL "STM32F411CEU6")
   set(STM32_C_FLAGS ${STM32_C_FLAGS} -DSTM32F4 -DSTM32F411CEU6 -D_ROM=512K -D_RAM=128K -D_ROM_OFF=0x08000000 -D_RAM_OFF=0x20000000)
   set(OPENCM3HAL_PATH ${CMAKE_CURRENT_LIST_DIR}/opencm3hal/stm32f4)
   set(LINKER_FILE ${OPENCM3HAL_PATH}/stm32f411xe.ld)
   target_link_libraries(${EXECUTABLE} opencm3_stm32f4)
else()
   message(FATAL_ERROR "Unknown CPU")
endif()

set(CMAKE_C_STANDARD 99)


target_compile_options(${EXECUTABLE} PRIVATE ${STM32_C_FLAGS})
target_include_directories(${EXECUTABLE} PRIVATE ${CMAKE_CURRENT_LIST_DIR} ${CMAKE_CURRENT_LIST_DIR}/opencm3hal)
target_sources(${EXECUTABLE} PRIVATE ${OPENCM3HAL_PATH}/hal.c)

target_link_options(${EXECUTABLE} PRIVATE ${STM32_LINK_FLAGS}
  -T${LINKER_FILE}
  -Wl,-Map=${PROJECT_NAME}.map
  )

add_custom_command(TARGET ${EXECUTABLE}
POST_BUILD
COMMAND ${CMAKE_SIZE} ${EXECUTABLE}.elf
WORKING_DIRECTORY ${PROJECT_BINARY_DIR})

add_custom_command(TARGET ${EXECUTABLE}
POST_BUILD
COMMAND ${CMAKE_OBJCOPY} -Obinary ${EXECUTABLE}.elf ${PROJECT_NAME}.bin
WORKING_DIRECTORY ${PROJECT_BINARY_DIR})

